"""Render an :class:`app.backtesting.adhoc.AdhocReport` to a PDF (bytes).

Uses matplotlib's Agg backend + PdfPages so it runs headless inside the API
worker with no browser and no system libraries. Kept deliberately plain:
a cover page of parameters + headline metrics + caveats, then equity /
drawdown, monthly returns + trade distribution, a per-symbol table, and a
trade log. matplotlib is imported lazily so it never slows app start-up.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from app.backtesting.adhoc import AdhocReport

_FOOT = "Generated by the trading platform · research only, not investment advice"


def _dt(s: Any) -> datetime | None:
    try:
        return datetime.fromisoformat(str(s).replace("Z", "+00:00").replace("+0530", "+05:30"))
    except ValueError:
        return None


def _money(v: Any) -> str:
    try:
        v = float(v)
    except (TypeError, ValueError):
        return str(v)
    sign = "-" if v < 0 else ""
    v = abs(v)
    if v >= 1e7:
        return f"{sign}₹{v / 1e7:.2f} Cr"
    if v >= 1e5:
        return f"{sign}₹{v / 1e5:.2f} L"
    return f"{sign}₹{v:,.0f}"


def render_pdf(report: AdhocReport) -> bytes:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages

    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        _cover_page(plt, pdf, report)
        _equity_page(plt, pdf, report)
        _distribution_page(plt, pdf, report)
        _per_symbol_page(plt, pdf, report)
        _trades_pages(plt, pdf, report)
        meta = pdf.infodict()
        meta["Title"] = f"{report.strategy_name} backtest report"
        meta["Subject"] = f"{', '.join(report.used_symbols)} · {report.start}..{report.end}"
        meta["CreationDate"] = datetime.now()
    return buf.getvalue()


def _footer(fig, page: int) -> None:
    fig.text(0.5, 0.02, f"{_FOOT}   ·   page {page}", ha="center", fontsize=7, color="#888")


def _cover_page(plt, pdf, r: AdhocReport) -> None:
    fig = plt.figure(figsize=(8.27, 11.69))  # A4 portrait
    fig.suptitle(f"{r.strategy_name}", fontsize=20, y=0.96, ha="center")
    fig.text(0.5, 0.925, "Backtest report", fontsize=12, ha="center", color="#555")

    lines = [
        ("Symbols", ", ".join(r.used_symbols) or "—"),
        ("Preset", r.preset),
        ("Timeframe", r.timeframe),
        ("Window", f"{r.start}  to  {r.end}"),
        ("Starting capital", _money(r.capital)),
        ("Generated", r.generated_at),
    ]
    if r.skipped:
        lines.append(("Skipped", ", ".join(s["symbol"] for s in r.skipped)))
    y = 0.87
    for k, v in lines:
        fig.text(0.10, y, f"{k}", fontsize=9, color="#666")
        fig.text(0.34, y, f"{v}", fontsize=9)
        y -= 0.022

    m = r.metrics
    rows = [
        ("Total return", f"{m.get('return_pct', 0):.2f}%"),
        ("CAGR", f"{m.get('cagr_pct', 0):.2f}%"),
        ("Sharpe", f"{m.get('sharpe_ratio', 0):.2f}"),
        ("Sortino", f"{m.get('sortino_ratio', 0):.2f}"),
        ("Max drawdown", f"{m.get('max_drawdown_pct', 0):.2f}%"),
        ("Calmar", f"{m.get('calmar_ratio', 0):.2f}"),
        ("Net P&L", _money(m.get("net_pnl", 0))),
        ("Total costs", _money(m.get("total_costs", 0))),
        ("Trades", str(m.get("total_trades", 0))),
        ("Win rate", f"{m.get('win_rate_pct', 0):.1f}%"),
        ("Profit factor", f"{m.get('profit_factor') if m.get('profit_factor') is not None else '∞'}"),
        ("Avg trade", _money(m.get("avg_trade", 0))),
        ("Avg winner", _money(m.get("avg_winner", 0))),
        ("Avg loser", _money(m.get("avg_loser", 0))),
        ("Largest winner", _money(m.get("largest_winner", 0))),
        ("Largest loser", _money(m.get("largest_loser", 0))),
    ]
    ax = fig.add_axes([0.10, 0.30, 0.80, 0.40])
    ax.axis("off")
    tbl = ax.table(
        cellText=[[k, v] for k, v in rows],
        colLabels=["Metric", "Value"],
        cellLoc="left", colLoc="left", loc="upper left",
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9)
    tbl.scale(1, 1.35)

    cav = "Caveats\n" + "\n".join(f"•  {c}" for c in r.caveats)
    fig.text(0.10, 0.06, cav, fontsize=7.5, color="#444", va="bottom", wrap=True)
    _footer(fig, 1)
    pdf.savefig(fig)
    plt.close(fig)


def _equity_page(plt, pdf, r: AdhocReport) -> None:
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8.27, 11.69), height_ratios=[3, 2])
    fig.subplots_adjust(top=0.92, bottom=0.08, left=0.12, right=0.95, hspace=0.28)

    eq = [(d, float(v)) for t, v in r.equity_curve if (d := _dt(t)) is not None]
    xs = [d for d, _ in eq]
    ys = [v for _, v in eq]
    if xs and ys:
        ax1.plot(xs, ys, lw=1.2, color="#1f77b4")
        ax1.axhline(r.capital, color="#aaa", lw=0.8, ls="--")
        ax1.fill_between(xs, ys, r.capital, where=[v >= r.capital for v in ys],
                         color="#1f77b4", alpha=0.08)
        ax1.set_title("Equity curve", fontsize=12, loc="left")
        ax1.set_ylabel("Portfolio value (₹)")
        ax1.grid(alpha=0.2)
        if ys:
            ax1.annotate(_money(ys[-1]), (xs[-1], ys[-1]), fontsize=8,
                         xytext=(-4, 4), textcoords="offset points", ha="right")

    dd = [(d, float(v)) for t, v in (r.charts.get("drawdown_curve") or [])
          if (d := _dt(t)) is not None]
    dxs = [d for d, _ in dd]
    dys = [v for _, v in dd]
    if dxs and dys:
        ax2.fill_between(dxs, dys, 0, color="#d62728", alpha=0.25)
        ax2.plot(dxs, dys, lw=1.0, color="#d62728")
        ax2.set_title("Drawdown (%)", fontsize=12, loc="left")
        ax2.set_ylabel("%")
        ax2.grid(alpha=0.2)
        ax2.annotate(f"{min(dys):.1f}%", (dxs[dys.index(min(dys))], min(dys)), fontsize=8)

    _footer(fig, 2)
    pdf.savefig(fig)
    plt.close(fig)


def _distribution_page(plt, pdf, r: AdhocReport) -> None:
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8.27, 11.69))
    fig.subplots_adjust(top=0.92, bottom=0.08, left=0.12, right=0.95, hspace=0.30)

    monthly: dict[str, float] = r.charts.get("monthly_returns") or {}
    if monthly:
        years = sorted({k[:4] for k in monthly})
        months = [f"{m:02d}" for m in range(1, 13)]
        grid = [[monthly.get(f"{y}-{m}", float("nan")) for m in months] for y in years]
        im = ax1.imshow(grid, aspect="auto", cmap="RdYlGn", vmin=-8, vmax=8)
        ax1.set_xticks(range(12), months)
        ax1.set_yticks(range(len(years)), years)
        ax1.set_title("Monthly return (%)", fontsize=12, loc="left")
        for i, row in enumerate(grid):
            for j, val in enumerate(row):
                if val == val:  # not NaN
                    ax1.text(j, i, f"{val:.1f}", ha="center", va="center", fontsize=6.5)
        fig.colorbar(im, ax=ax1, fraction=0.03, pad=0.02)
    else:
        ax1.axis("off")
        ax1.text(0.5, 0.5, "no monthly data", ha="center", color="#999")

    rets = [t.get("return_pct") for t in r.trades if isinstance(t.get("return_pct"), (int, float))]
    if rets:
        ax2.hist(rets, bins=min(40, max(8, len(rets) // 2)), color="#1f77b4", alpha=0.8)
        ax2.axvline(0, color="#d62728", lw=1)
        ax2.set_title("Per-trade return distribution (%)", fontsize=12, loc="left")
        ax2.set_xlabel("return %")
        ax2.set_ylabel("trades")
        ax2.grid(alpha=0.2)
    else:
        ax2.axis("off")
        ax2.text(0.5, 0.5, "no closed trades", ha="center", color="#999")

    _footer(fig, 3)
    pdf.savefig(fig)
    plt.close(fig)


def _per_symbol_page(plt, pdf, r: AdhocReport) -> None:
    fig = plt.figure(figsize=(8.27, 11.69))
    fig.suptitle("Per-symbol breakdown", fontsize=13, y=0.95)
    ax = fig.add_axes([0.07, 0.08, 0.86, 0.82])
    ax.axis("off")
    rows = [
        [s.symbol, str(s.trades), f"{s.win_rate_pct:.0f}%", _money(s.net_pnl),
         _money(s.avg_trade), _money(s.largest_winner), _money(s.largest_loser)]
        for s in r.per_symbol
    ] or [["—", "0", "—", "—", "—", "—", "—"]]
    tbl = ax.table(
        cellText=rows,
        colLabels=["Symbol", "Trades", "Win%", "Net P&L", "Avg", "Best", "Worst"],
        cellLoc="center", loc="upper center",
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8)
    tbl.scale(1, 1.3)
    _footer(fig, 4)
    pdf.savefig(fig)
    plt.close(fig)


def _trades_pages(plt, pdf, r: AdhocReport) -> None:
    trades = r.trades
    if not trades:
        return
    per_page = 34
    page = 5
    for start in range(0, min(len(trades), 340), per_page):
        chunk = trades[start:start + per_page]
        fig = plt.figure(figsize=(8.27, 11.69))
        fig.suptitle(f"Trade log  ({start + 1}–{start + len(chunk)} of {len(trades)})",
                     fontsize=12, y=0.96)
        ax = fig.add_axes([0.05, 0.05, 0.90, 0.87])
        ax.axis("off")
        rows = []
        for t in chunk:
            rows.append([
                str(t.get("instrument", "")),
                str(t.get("direction", "")),
                str(t.get("quantity", "")),
                f"{t.get('entry_price', 0):.2f}",
                f"{t.get('exit_price', 0):.2f}",
                _money(t.get("net_pnl", 0)),
                f"{t.get('return_pct', 0):.2f}%",
            ])
        tbl = ax.table(
            cellText=rows,
            colLabels=["Symbol", "Dir", "Qty", "Entry", "Exit", "Net P&L", "Ret%"],
            cellLoc="center", loc="upper center",
        )
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(7)
        tbl.scale(1, 1.25)
        _footer(fig, page)
        pdf.savefig(fig)
        plt.close(fig)
        page += 1
