"""paper strategy runs

Revision ID: 0bff26c099a3
Revises: 9b1abb5f5053
Create Date: 2026-09-03 14:04:18.949341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0bff26c099a3'
down_revision: Union[str, None] = '9b1abb5f5053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_strategy_runs',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instruments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('product', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('flatten_on_stop', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bar_ts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', sa.Integer(), nullable=False),
    sa.Column('orders_placed', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_strat_acct_status', 'paper_strategy_runs', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_paper_strategy_runs_account_id'), 'paper_strategy_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_strategy_runs_status'), 'paper_strategy_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_strategy_runs_status'), table_name='paper_strategy_runs')
    op.drop_index(op.f('ix_paper_strategy_runs_account_id'), table_name='paper_strategy_runs')
    op.drop_index('ix_paper_strat_acct_status', table_name='paper_strategy_runs')
    op.drop_table('paper_strategy_runs')
    # ### end Alembic commands ###
