"""scanner context + paper algo config

Revision ID: 0c7269141e7d
Revises: ff824cb6f066
Create Date: 2026-09-03 14:41:30.750312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0c7269141e7d'
down_revision: Union[str, None] = 'ff824cb6f066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_algo_config',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_grade', sa.String(length=1), nullable=False),
    sa.Column('pct_per_trade', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_open_auto', sa.Integer(), nullable=False),
    sa.Column('daily_loss_stop_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cutoff_ist', sa.String(length=5), nullable=False),
    sa.Column('allow_delivery', sa.Boolean(), nullable=False),
    sa.Column('allow_intraday', sa.Boolean(), nullable=False),
    sa.Column('allow_options', sa.Boolean(), nullable=False),
    sa.Column('equity_product', sa.String(length=4), nullable=False),
    sa.Column('halted_reason', sa.String(length=200), nullable=True),
    sa.Column('halted_day', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_algo_config_account_id'), 'paper_algo_config', ['account_id'], unique=False)
    op.add_column('scan_recommendations', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_recommendations', 'context')
    op.drop_index(op.f('ix_paper_algo_config_account_id'), table_name='paper_algo_config')
    op.drop_table('paper_algo_config')
    # ### end Alembic commands ###
