"""market scanner recommendation engine

Revision ID: 42cf256913a7
Revises: b8e4d1a06c33
Create Date: 2026-09-03 10:06:06.632452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '42cf256913a7'
down_revision: Union[str, None] = 'b8e4d1a06c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.String(length=12), nullable=False),
    sa.Column('data_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('scanned', sa.Integer(), nullable=False),
    sa.Column('produced', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('skipped', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_runs_started', 'scan_runs', ['started_at'], unique=False)
    op.create_table('scan_recommendations',
    sa.Column('scan_run_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_token', sa.String(length=24), nullable=False),
    sa.Column('segment', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('underlying', sa.String(length=64), nullable=True),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('setup_type', sa.String(length=48), nullable=False),
    sa.Column('setup_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ref_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('entry', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_1', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_2', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rr', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('atr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('bias_score', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('pop', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('option_overlay', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fundamentals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('outcome', sa.String(length=12), nullable=True),
    sa.Column('trading_day', sa.String(length=10), nullable=False),
    sa.Column('entered_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('result_r', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('result_points', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mfe_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mae_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_ltp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_state', sa.String(length=8), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_reco_status_day', 'scan_recommendations', ['status', 'trading_day'], unique=False)
    op.create_index('ix_scan_reco_symbol_day', 'scan_recommendations', ['tradingsymbol', 'trading_day'], unique=False)
    op.create_index(op.f('ix_scan_recommendations_status'), 'scan_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_scan_recommendations_trading_day'), 'scan_recommendations', ['trading_day'], unique=False)
    op.create_table('scanner_alerts',
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['scan_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scanner_alerts_created', 'scanner_alerts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scanner_alerts_created', table_name='scanner_alerts')
    op.drop_table('scanner_alerts')
    op.drop_index(op.f('ix_scan_recommendations_trading_day'), table_name='scan_recommendations')
    op.drop_index(op.f('ix_scan_recommendations_status'), table_name='scan_recommendations')
    op.drop_index('ix_scan_reco_symbol_day', table_name='scan_recommendations')
    op.drop_index('ix_scan_reco_status_day', table_name='scan_recommendations')
    op.drop_table('scan_recommendations')
    op.drop_index('ix_scan_runs_started', table_name='scan_runs')
    op.drop_table('scan_runs')
    # ### end Alembic commands ###
