"""market scanner trade_style

Revision ID: 91bf46f9a377
Revises: 42cf256913a7
Create Date: 2026-09-03 11:39:47.562538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91bf46f9a377'
down_revision: Union[str, None] = '42cf256913a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add with a server default so existing rows backfill, then drop the
    # default (the ORM sets the value on every insert going forward)
    op.add_column(
        'scan_recommendations',
        sa.Column('trade_style', sa.String(length=20), nullable=False,
                  server_default='EQUITY_DELIVERY'),
    )
    op.alter_column('scan_recommendations', 'trade_style', server_default=None)
    op.create_index(op.f('ix_scan_recommendations_trade_style'), 'scan_recommendations', ['trade_style'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_recommendations_trade_style'), table_name='scan_recommendations')
    op.drop_column('scan_recommendations', 'trade_style')
    # ### end Alembic commands ###
