"""paper trading account

Revision ID: 9b1abb5f5053
Revises: ce024259e820
Create Date: 2026-09-03 13:45:01.404764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b1abb5f5053'
down_revision: Union[str, None] = 'ce024259e820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('charges_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('auto_squareoff_mis', sa.Boolean(), nullable=False),
    sa.Column('last_eod_day', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_holdings',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_token', sa.String(length=24), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('t1_qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_hold_key', 'paper_holdings', ['account_id', 'tradingsymbol'], unique=False)
    op.create_index(op.f('ix_paper_holdings_account_id'), 'paper_holdings', ['account_id'], unique=False)
    op.create_table('paper_ledger',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_ledger_account_id'), 'paper_ledger', ['account_id'], unique=False)
    op.create_index('ix_paper_ledger_acct_time', 'paper_ledger', ['account_id', 'at'], unique=False)
    op.create_table('paper_orders',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_token', sa.String(length=24), nullable=True),
    sa.Column('segment', sa.String(length=24), nullable=True),
    sa.Column('asset_class', sa.String(length=12), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=6), nullable=False),
    sa.Column('product', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('status_message', sa.String(length=300), nullable=True),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_squareoff', sa.Boolean(), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_account_id'), 'paper_orders', ['account_id'], unique=False)
    op.create_index('ix_paper_orders_acct_status', 'paper_orders', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_paper_orders_status'), 'paper_orders', ['status'], unique=False)
    op.create_table('paper_positions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_token', sa.String(length=24), nullable=True),
    sa.Column('segment', sa.String(length=24), nullable=True),
    sa.Column('asset_class', sa.String(length=12), nullable=False),
    sa.Column('product', sa.String(length=4), nullable=False),
    sa.Column('net_qty', sa.Integer(), nullable=False),
    sa.Column('buy_qty', sa.Integer(), nullable=False),
    sa.Column('sell_qty', sa.Integer(), nullable=False),
    sa.Column('buy_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sell_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('charges', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin_blocked', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trading_day', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_pos_key', 'paper_positions', ['account_id', 'tradingsymbol', 'product', 'status'], unique=False)
    op.create_index(op.f('ix_paper_positions_account_id'), 'paper_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_status'), 'paper_positions', ['status'], unique=False)
    op.create_index(op.f('ix_paper_positions_trading_day'), 'paper_positions', ['trading_day'], unique=False)
    op.create_table('paper_trades',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=12), nullable=False),
    sa.Column('product', sa.String(length=4), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('charges', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('charges_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_account_id'), 'paper_trades', ['account_id'], unique=False)
    op.create_index('ix_paper_trades_acct_time', 'paper_trades', ['account_id', 'traded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_trades_acct_time', table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_account_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_paper_positions_trading_day'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_status'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_account_id'), table_name='paper_positions')
    op.drop_index('ix_paper_pos_key', table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_paper_orders_status'), table_name='paper_orders')
    op.drop_index('ix_paper_orders_acct_status', table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_account_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index('ix_paper_ledger_acct_time', table_name='paper_ledger')
    op.drop_index(op.f('ix_paper_ledger_account_id'), table_name='paper_ledger')
    op.drop_table('paper_ledger')
    op.drop_index(op.f('ix_paper_holdings_account_id'), table_name='paper_holdings')
    op.drop_index('ix_paper_hold_key', table_name='paper_holdings')
    op.drop_table('paper_holdings')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
