"""market scanner strict score + hedge + pair

Revision ID: ce024259e820
Revises: 91bf46f9a377
Create Date: 2026-09-03 13:11:49.564159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ce024259e820'
down_revision: Union[str, None] = '91bf46f9a377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_recommendations', sa.Column('score_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scan_recommendations', sa.Column('hedge', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scan_recommendations', sa.Column('pair_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_scan_recommendations_pair_id'), 'scan_recommendations', ['pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_recommendations_pair_id'), table_name='scan_recommendations')
    op.drop_column('scan_recommendations', 'pair_id')
    op.drop_column('scan_recommendations', 'hedge')
    op.drop_column('scan_recommendations', 'score_detail')
    # ### end Alembic commands ###
