"""initial schema

Revision ID: fbc207bdd7c7
Revises: 
Create Date: 2026-09-01 15:10:51.454321

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'fbc207bdd7c7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'DEPLOY', 'STOP', 'PAUSE', 'RESUME', 'CLONE', 'ORDER_PLACED', 'ORDER_REJECTED', 'LOGIN', 'LOGOUT', 'RISK_BREACH', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.Enum('STRATEGY', 'STRATEGY_VERSION', 'DEPLOYMENT', 'RISK_CONFIG', 'BROKER_SESSION', name='changeentitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('BACKTEST', 'SIMULATION', 'PAPER', 'LIVE', name='tradingmode'), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('broker_sessions',
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('kite_user_id', sa.String(length=50), nullable=True),
    sa.Column('access_token_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('public_token', sa.String(length=200), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_log_entries',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.Enum('STRATEGY', 'STRATEGY_VERSION', 'DEPLOYMENT', 'RISK_CONFIG', 'BROKER_SESSION', name='changeentitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_log_entries_created_at'), 'change_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_change_log_entries_entity_id'), 'change_log_entries', ['entity_id'], unique=False)
    op.create_table('strategies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='strategystatus'), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_point', sa.String(length=200), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('cloned_from_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloned_from_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_versions_strategy_id_version', 'strategy_versions', ['strategy_id', 'version_number'], unique=True)
    # strategies.current_version_id -> strategy_versions.id is a circular
    # reference (strategy_versions.strategy_id -> strategies.id already
    # exists), so it must be added as a separate ALTER TABLE once both
    # tables exist rather than inline on either CREATE TABLE.
    op.create_foreign_key(
        'fk_strategies_current_version_id_strategy_versions',
        'strategies', 'strategy_versions', ['current_version_id'], ['id'],
    )
    op.create_table('backtests',
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backteststatus'), nullable=False),
    sa.Column('instrument_universe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('BACKTEST', 'SIMULATION', 'PAPER', 'LIVE', name='tradingmode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'STOPPED', 'ERROR', name='deploymentstatus'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instrument_universe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('live_trading_confirmed', sa.Boolean(), nullable=False),
    sa.Column('live_trading_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cloned_from_deployment_id', sa.UUID(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloned_from_deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('mode', sa.Enum('BACKTEST', 'SIMULATION', 'PAPER', 'LIVE', name='tradingmode'), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('backtest_id', sa.UUID(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=50), nullable=True),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='ordertransactiontype'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'SL', 'SL_M', name='ordertype'), nullable=False),
    sa.Column('product', sa.Enum('CNC', 'MIS', 'NRML', 'MTF', name='producttype'), nullable=False),
    sa.Column('variety', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_protection', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'COMPLETE', 'REJECTED', 'CANCELLED', 'ERROR', name='orderstatus'), nullable=False),
    sa.Column('status_message', sa.String(length=1000), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(deployment_id IS NOT NULL) OR (backtest_id IS NOT NULL)', name='ck_orders_has_deployment_or_backtest'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_table('trades',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('BACKTEST', 'SIMULATION', 'PAPER', 'LIVE', name='tradingmode'), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=50), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fill_quantity', sa.Integer(), nullable=False),
    sa.Column('fill_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('deployments')
    op.drop_table('backtests')
    op.drop_constraint(
        'fk_strategies_current_version_id_strategy_versions', 'strategies', type_='foreignkey'
    )
    op.drop_index('ix_strategy_versions_strategy_id_version', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_change_log_entries_entity_id'), table_name='change_log_entries')
    op.drop_index(op.f('ix_change_log_entries_created_at'), table_name='change_log_entries')
    op.drop_table('change_log_entries')
    op.drop_table('broker_sessions')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    # Postgres ENUM types created by sa.Enum columns are NOT dropped by
    # drop_table — without this, a downgrade-then-upgrade cycle fails with
    # "type already exists" on the next CREATE TYPE.
    for enum_name in (
        'orderstatus', 'producttype', 'ordertype', 'ordertransactiontype',
        'deploymentstatus', 'backteststatus', 'strategystatus',
        'tradingmode', 'changeentitytype', 'auditaction',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
