"""widen paper order tag

Revision ID: ff824cb6f066
Revises: 0bff26c099a3
Create Date: 2026-09-03 14:09:19.801007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff824cb6f066'
down_revision: Union[str, None] = '0bff26c099a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_orders', 'tag',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_orders', 'tag',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
